### ISSUE TITLE
Express 5.0 - last push!

### ISSUE THREAD

**Issue by UlisesGascon** [expressjs/discussions#233]
This issue includes a reference to all the PRs/issues or pending tasks for Express and dependencies needed to finally ship Express@5.

### Rules (WIP):
- If something is completed, just marked
- If there is a PR/Issue/Discussion please add it (try to use one item)
- If there is someone taking ownership on it, please add it. Ownership means to be the focal point for it not necessarily the person who makes the final change.
- If there is no leader, feel free to claim it.
- If you can no longer lead something, just let others claim it back 
- As this issue can have many comments, feel free to address them and then mark the original comment as "outdated" ([details](https://docs.github.com/en/communities/moderating-comments-and-conversations/managing-disruptive-comments#hiding-a-comment)) so it is easier to follow.

If you think that any reference is missing, please edit this comment (@expressjs/express-tc) or reply with a comment if you don't have the permissions.

### Pending things (Express):

- [x] https://github.com/expressjs/express/pull/5627 (@mertcanaltin)
- [x] https://github.com/expressjs/express/pull/5595 (@UlisesGascon )
- [x] https://github.com/expressjs/express/pull/4861
- [x] https://github.com/expressjs/express/pull/5792 (@jonchurch)
- [x] https://github.com/expressjs/express/pull/4835 
- [x] https://github.com/expressjs/express/pull/4212 (@jonchurch)
- [x] https://github.com/expressjs/express/pull/3216 (@wesleytodd)
- [x] https://github.com/expressjs/expressjs.com/issues/1464 (@crandmck)
- [x] https://github.com/expressjs/expressjs.com/issues/1408 (@blakeembrey )
- [x] https://github.com/expressjs/express/pull/5677 (@ulisesgascon )
- [x] https://github.com/expressjs/discussions/issues/256 (@ulisesgascon / @IamLizu)

### Pending things (Dependencies):

- [x] https://github.com/expressjs/express/pull/5885 (@wesleytodd)
  - [x] https://github.com/pillarjs/router/pull/117
  - [x] https://github.com/pillarjs/router/pull/60
- [x] https://github.com/expressjs/body-parser/pull/66 (@wesleytodd)
- [x] https://github.com/expressjs/body-parser/pull/406 (@wesleytodd or @UlisesGascon or TBD)
- [x] https://github.com/expressjs/body-parser/pull/387 (@wesleytodd)
- [x] https://github.com/expressjs/body-parser/pull/326 (@wesleytodd)
- [x] https://github.com/pillarjs/send/pull/208 (~@blakeembrey or~ @wesleytodd ~its a race~)
- [x] https://github.com/expressjs/serve-static/pull/165 (@wesleytodd)
- [x] https://github.com/jshttp/mime-types/pull/129 (@wesleytodd)
  - [x] https://github.com/expressjs/express/pull/5882
  - [x] https://github.com/expressjs/express/pull/5881
  - [x] https://github.com/expressjs/express/pull/5883
- [x] https://github.com/expressjs/express/pull/5899
  - [x] https://github.com/pillarjs/finalhandler/pull/55
  - [x] https://github.com/pillarjs/finalhandler/pull/57
- [x] https://github.com/jshttp/fresh/pull/38 (@jonchurch)
- [x] Look through the direct deps to see if they have things which need to land,, or releases to cut, untracked WORK! (@wesleytodd)
- [x] Ensure each of the dependencies updates their transitives

 
### Pending things (Documentation):
- [x] https://github.com/expressjs/expressjs.com/issues/1483 It will great to do an announcement in the blog about the release and celebrate this big milestone for the project :partying_face: (@UlisesGascon )
- [ ] https://github.com/expressjs/expressjs.com/issues/1466 Should be offer a fresh version when v5 is ready? (@UlisesGascon )
- [ ] https://github.com/expressjs/expressjs.com/issues/1479 (@UlisesGascon )

### Discussions pending:
**New**

- [ ] Express Generator? [Context](https://github.com/expressjs/discussions/issues/233#issuecomment-2102971156)

**Under Investigation**
- [ ] https://github.com/expressjs/express/pull/2692 (@blakeembrey )
- [ ] https://github.com/expressjs/express/pull/2653 (@blakeembrey )

### Decisions made:

**Not in 5.x**
- [ ] https://github.com/expressjs/express/pull/3730
- [ ] https://github.com/expressjs/express/pull/3214
- [ ] https://github.com/expressjs/express/pull/3218
- [ ] https://github.com/expressjs/express/pull/3213
- [ ] https://github.com/expressjs/express/pull/2648
- [ ] https://github.com/expressjs/body-parser/pull/524
- [ ] https://github.com/jshttp/on-finished/pull/31 (@UlisesGascon)

**Future Minors**

- [ ] https://github.com/expressjs/express/pull/5856 (@aagamezl)
- [ ] https://github.com/expressjs/express/pull/5492 (@UlisesGascon )
- [ ] https://github.com/expressjs/express/pull/3259 (@wesleytodd)

**Comment by wesleytodd** [comment]
Awesome! Was this list pulled from those labels? One thing we probably need to add as a TODO is to go through all of the direct dependencies and ensure they all have correctly triaged ones which should land before v5, or did you do that as well? It is hard to tell from the list but I dont see any body parser issues in here and I could have sworn there was some pending work to land in there?

**Comment by UlisesGascon** [comment]
> Awesome! Was this list pulled from those labels?

This was done manually. I quickly reviewed the `express` and `expressjs.com` repositories. If anything is missing from dependencies, please feel free to add them. The list may not be exhaustive at this point, but it's a great starting point and compass to help us focus on v5.x. You made a great suggestion with this approach :raised_hands: 

Let's also see if the @expressjs/triagers can help us find missing items on the list and assist in reviewing PRs and taking leadership in some of them (I see a few PRs that require conflict resolution, updates...).

**Comment by CBID2** [comment]
Can I do the "Add the blog one" @UlisesGascon?

**Comment by wesleytodd** [comment]
Yeah this is great! Absolutely agree with getting folks involved in taking ownership of them. Go team!

> If anything is missing from dependencies, please feel free to add them. 

Ok yeah this was my main concern. I knew for sure there is router stuff which is why I started there with the labels, but I think there is more in the other few. So if anyone wants to take point on reviewing the deps we own which are "direct deps" of `express` that would be awesome. Specifically I think each repo needs to address if there are any pending breaking changes which look like they were ready to land (if they are too contentious or too incomplete then we should not land them now) or if there is a pre-existing major version branch with work left to do on it (which is the case in a few for sure). For that we need to catalog that work here so we make sure we don't miss anything.

**Comment by jonchurch** [comment]
Active dev branch for v5 is [`5.x`](https://github.com/expressjs/express/tree/5.x), correct?

**Comment by mertcanaltin** [comment]
> "Blogu ekle" seçeneğini yapabilir miyim?@UlisesGascon?

I can help you :rocket:

**Comment by mertcanaltin** [comment]
> Can I do the "Add the blog one" @UlisesGascon?

I can help you 🚀

**Comment by mertcanaltin** [comment]
Add support for Node@22 in the CI (no leader), would like to work with this topic

**Comment by UlisesGascon** [comment]
> Can I do the "Add the blog one" @UlisesGascon?

I think that @chrisdel101 is actively working on it, maybe we can provide them more support.

Aside of active development for sure you (@CBID2  @mertcanaltin) can work on:
- Reviewing the PR(s) for the new blog
- Start to work on the blog entries content (see: https://github.com/expressjs/expressjs.com/issues/1500)

> Add support for Node@22 in the CI (no leader), would like to work with this topic. 

I think that maybe @rxmarbles is working on it, based on [slack comment](https://openjs-foundation.slack.com/archives/C07019ZKWQ4/p1713783722877429)

**Comment by Yaminyam** [comment]
I'm very excited about the new version of express being released!
https://github.com/expressjs/generator I think it would be better if this repo was also maintained.
I think that the current code written using syntax prior to ES2015 is very outdated.
(ref: https://github.com/expressjs/generator/pull/200)

**Comment by wesleytodd** [comment]
Hey @Yaminyam, that package is on our radar but we need to do the necessary here first. I believe there is a tracking issue for it here: https://github.com/expressjs/discussions/issues/197

**Comment by wesleytodd** [comment]
@jonchurch do you think this needs to be added to the list above? https://github.com/expressjs/express/issues/4851

**Comment by wesleytodd** [comment]
I reviewed the remaining open things in `body-parser`. I added them to the list here, but likely will want to update the linked v2 PR as well. I dont have enough remaining battery on this plane to be able to start work on them, and also I think some are a bit ambigious as to what we need to do to get it across the finish line. Would love if folks could click through some of the ones I added and add any insight or thoughts they have on them and if we need to land them.

**Comment by jdhiro** [comment]
Why are there so many "bonus" dependencies on the 5.0 release the community has been waiting on for YEARS? (Brotli support?!)

5.0 literally needs two things:
* Async error handling.
* Official Typescript typings.

That's it. Add those and ship it -- for the love of God.

**Comment by RobinTail** [comment]
@wesleytodd , would it be possible to detach features from the breaking changes needed for those features in order to speed up the release of `5.0`?

The `brotli` support could be a feature of `5.1`, isn't it? While dropping Node versions below 18 must be prioritised to enable and ease implementing new features of `5.x`. 

It's been 10 years.

![2024-07-03_11-30-59](https://github.com/expressjs/discussions/assets/13189514/4d298449-0c58-4ad8-93c5-42f68b95574b)

**Comment by ctcpip** [comment]
A number of things have been punted from the initial `5.0` release, and more may yet be punted, where possible.

**Comment by wesleytodd** [comment]
Ok, I just checked off an important one: "Look through the direct deps to see if they have things which need to land"

I have gone through and commented on or resolved as many of the PR's/issues/discussions in the direct and transitives which seem to have some pending (breaking) changes to land. I added a few things on the list, but they are relatively small and should be simple enough to resolve.

**Comment by IamLizu** [comment]
Here's the list of dependencies needing upgrade,

- [ ] cookie-signature - used 1.0.6 - current 1.2.1
- [ ] debug - used 3.1.0 - current 4.3.6
- [ ] merge-descriptors - used 1.0.1 - current 2.0.0 (may be fixed by https://github.com/expressjs/express/pull/5782)
- [ ] qs - used 6.11.0 - current 6.13.0

**Comment by kibertoad** [comment]
@IamLizu How about replacing `qs` with `neoqs`? https://github.com/puruvj/neoqs

**Comment by wesleytodd** [comment]
Hey @kibertoad, can we keep the discussion on that issue in the PR already created? These are just updates of existing deps. I hit the comments as "off topic".

**Comment by RobinTail** [comment]
Thank you @wesleytodd , @UlisesGascon , @ctcpip and others!
This is an epic achievement on the planetary scale.
❤️

**Comment by wesleytodd** [comment]
We put a closes line in the commit, but looks like it didnt actually close this. So I can happily say this is closed as completed!

**Comment by ctcpip** [comment]
resolved via https://github.com/expressjs/express/pull/2237
