### ISSUE TITLE
Backlog Express 5.x

### ISSUE THREAD

**Issue by UlisesGascon** [expressjs/discussions#266]
This issue includes a reference to all the PRs/issues or pending tasks for Express and dependencies needed to finally ship new versions of  Express@5.x

### Rules (WIP):
- If something is completed, just marked
- If there is a PR/Issue/Discussion please add it (try to use one item)
- If there is someone taking ownership on it, please add it. Ownership means to be the focal point for it not necessarily the person who makes the final change.
- If there is no leader, feel free to claim it.
- If you can no longer lead something, just let others claim it back 
- As this issue can have many comments, feel free to address them and then mark the original comment as "outdated" ([details](https://docs.github.com/en/communities/moderating-comments-and-conversations/managing-disruptive-comments#hiding-a-comment)) so it is easier to follow.

If you think that any reference is missing, please edit this comment (@expressjs/express-tc) or reply with a comment if you don't have the permissions.

### Bugs reported on 5.x
- [x] https://github.com/expressjs/express/issues/5948

### Pending things (Documentation):
- [ ] https://github.com/expressjs/expressjs.com/issues/1466 Should be offer a fresh version when v5 is ready? (@UlisesGascon )
- [ ] https://github.com/expressjs/expressjs.com/issues/1479 (@UlisesGascon )

### Pending for 5.1.0

- [ ] https://github.com/expressjs/express/pull/5856 (@aagamezl)
- [ ] https://github.com/expressjs/express/pull/5492 (@UlisesGascon )
- [ ] https://github.com/expressjs/express/pull/3259 (@wesleytodd)

### Discussions pending:
**New**

- [ ] https://github.com/expressjs/express/discussions/5961
- [ ] Let's provide clear details: https://github.com/expressjs/express/issues/5944
- [ ] Express Generator? [Context](https://github.com/expressjs/discussions/issues/233#issuecomment-2102971156)

**Under Investigation**
- [ ] https://github.com/expressjs/express/pull/2653 (@blakeembrey )

**Comment by jonchurch** [comment]
High prio rn in this order:

* Changelog
* Docs
* Migration guide

**Comment by ex1st** [comment]
I'm not sure if this is a bug, so I created the question in discussions https://github.com/expressjs/express/discussions/5961

**Comment by heidemn-faro** [comment]
Not sure if this is a bug, but seems at least worth mentioning in the migration docs: https://github.com/expressjs/express/issues/6191

**Comment by bjohansebas** [comment]
https://github.com/expressjs/express/pull/3714 Maybe this for version 5.2? It looks interesting, if Wes can't continue it, i could.
